Este es el proyecto de predictor de precio de un ordenador portátil. Voy a aplicar los conocimientos aprendidos sobre Aprendizaje Supervisado y Regresión Lineal del curso de Andrew Ng.

# 1. Importaciones de librerías necesarias

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# 2. Cargar los datos

In [23]:
df = pd.read_csv('laptop_data.csv')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   str
 2   TypeName          1303 non-null   str
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   str
 5   Cpu               1303 non-null   str
 6   Ram               1303 non-null   str
 7   Memory            1303 non-null   str
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   str
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 122.3 KB

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [24]:
# Separación de datos

# Voy a descartar las columnas de GPU y OpSys
df = df.drop(columns=['Gpu', 'OpSys', 'TypeName', 'ScreenResolution', 'Unnamed: 0'])

In [25]:
# Primero limpio las columnas para que sean solo números (borrar unidades)
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

# Implemento una función para extraer los GB de Memory
def gb_memory(texto):
    texto = str(texto)
    if 'TB' in texto:
        num = float(texto.split('TB')[0].split()[-1])
        return int(num * 1024) # Lo devuelvo en GB
    elif 'GB' in texto:
        num = float(texto.split('GB')[0].split()[-1])
        return int(num)

df['Memory'] = df['Memory'].apply(gb_memory) 

# Función para limpiar la columna Cpu
def procesadores(texto):
    texto = str(texto)
    if 'Intel Core i7' in texto:
        return 'Intel Core i7'
    elif 'Intel Core i5' in texto:
        return 'Intel Core i5'
    elif 'Intel Core i3' in texto:
        return 'Intel Core i3'
    elif 'Intel' in texto:
        return 'Otros Intel'
    elif 'AMD' in texto: 
        return 'AMD'
    else:
        return None

df['Cpu'] = df['Cpu'].apply(procesadores)

def eliminar_companys(df):
    marcas = ['Apple', 'Asus', 'HP', 'Dell', 'Lenovo']
    df_filtrado = df[df['Company'].isin(marcas)].copy()
    df_filtrado = df_filtrado.reset_index(drop=True) #Reseteo los index
    return df_filtrado

df = eliminar_companys(df)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1047 entries, 0 to 1046
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  1047 non-null   str
 1   Inches   1047 non-null   float64
 2   Cpu      1047 non-null   str
 3   Ram      1047 non-null   int64
 4   Memory   1047 non-null   int64
 5   Weight   1047 non-null   float64
 6   Price    1047 non-null   float64
dtypes: float64(3), int64(2), str(2)
memory usage: 57.4 KB

  Company  Inches            Cpu  Ram  Memory  Weight        Price
0   Apple    13.3  Intel Core i5    8     128    1.37   71378.6832
1   Apple    13.3  Intel Core i5    8     128    1.34   47895.5232
2      HP    15.6  Intel Core i5    8     256    1.86   30636.0000
3   Apple    15.4  Intel Core i7   16     512    1.83  135195.3360
4   Apple    13.3  Intel Core i5    8     256    1.37   96095.8080

In [26]:
# Ahora aplico get_dummies a Company y Cpu para que todo el dataset sean numeros
df_procesado = pd.get_dummies(df, columns=['Company', 'Cpu'], drop_first=True, dtype=int)
    # drop_first elimina la columna original sobre la que se aplica get_dummies
    # dtype hace que las columnas que se creen sean int, por defecto son booleanas

df_procesado.head()

,Inches,Ram,Memory,Weight,Price,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,Cpu_Intel Core i3,Cpu_Intel Core i5,Cpu_Intel Core i7,Cpu_Otros Intel
0,13.3,8,128,1.37,71378.6832,0,0,0,0,0,1,0,0
1,13.3,8,128,1.34,47895.5232,0,0,0,0,0,1,0,0
2,15.6,8,256,1.86,30636.0000,0,0,1,0,0,1,0,0
3,15.4,16,512,1.83,135195.3360,0,0,0,0,0,0,1,0
4,13.3,8,256,1.37,96095.8080,0,0,0,0,0,1,0,0

Ya tengo todo el dataset limpio y preparado. Ahora voy a separarlo en X e y, y en train y test.

In [27]:
X = df_procesado.drop(columns=['Price']).values
y = df_procesado['Price'].values

print(f"Dimensiones de X: {X.shape}")
print(f"Dimensiones de y: {y.shape}")

Dimensiones de X: (1047, 12)
Dimensiones de y: (1047,)

In [28]:
# Ahora separo los conjuntos de TRAIN y TEST
# uso el método train_test_split de scikit-learn

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Ejemplos para entrenar (test): {X_train.shape}")
print(f"Ejemplos para probar (test): {X_test.shape}")

Ejemplos para entrenar (test): (837, 12)
Ejemplos para probar (test): (210, 12)

# HOJA DE RUTA DEL PROYECTO

1. Limpieza y transformación de los datos
2. Separación de variables y escalado
3. Programar el algoritmo desde cero
4. Entrenamiento y diagnóstico
5. Comparación con scikit-learn